### ISSUE TITLE
Plugin throws exception when refactoring constant to upper case with underscore.

### ISSUE THREAD

**Issue by lchloride** [XenoAmess/p3c#118]
**Describe the bug**
Plugin throws exception when refactoring constant to upper case with underscore.

**To Reproduce**
1. Has a constant field with Camel-case, and a warning shows `Constant [XXX] should be written in upper characters separated by underscores `
2. Try to fix this by `Refactor to upper case with underscore.`
3. The constant is refactored however an exception occurred.

**Expected behavior**
No exception occurred.

**Screenshots**
![Refactor](https://user-images.githubusercontent.com/22909207/125548289-bc7af3fc-85e9-4162-8d68-3bd8967270ee.png)

![IDE fatal error](https://user-images.githubusercontent.com/22909207/125547612-df51d209-30c1-40cf-8fe5-8c8dacd2dfe7.png)

```text
java.lang.Throwable: Do not call commitAllDocumentsUnderProgress inside write-action
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAllDocumentsUnderProgress(PsiDocumentManagerBase.java:228)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.commitAllDocumentsUnderProgress(PsiDocumentManagerImpl.java:204)
	at com.intellij.refactoring.actions.RenameElementAction.actionPerformed(RenameElementAction.java:64)
	at com.alibaba.p3c.idea.quickfix.AliQuickFix$Companion.doQuickFix(AliQuickFix.kt:76)
	at com.alibaba.p3c.idea.quickfix.ConstantFieldShouldBeUpperCaseQuickFix.applyFix(ConstantFieldShouldBeUpperCaseQuickFix.kt:46)
	at com.alibaba.p3c.idea.quickfix.ConstantFieldShouldBeUpperCaseQuickFix.applyFix(ConstantFieldShouldBeUpperCaseQuickFix.kt:30)
	at com.intellij.codeInspection.ex.QuickFixWrapper.invoke(QuickFixWrapper.java:78)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.lambda$invoke$0(IntentionActionWithTextCaching.java:209)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:209)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$4(ShowIntentionActionsHandler.java:251)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:105)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:947)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:973)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:104)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:251)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:227)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:226)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$3(IntentionListStep.java:135)
	at com.intellij.ide.IdeEventQueue.onFocusEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Desktop (please complete the following information):**
 - OS: MacOS 10.14
 - IDE: IDEA Ultimate 2021.1.3
 - Version: 2.1.0.6

**Comment by XenoAmess** [comment]
Hi.
I thought we fixed, or at least make it not log error anymore...
https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-/versions/stable/129152
please wait for at most 2 days for checking by jetbrains.
