### ISSUE TITLE
使用符号链接打开项目时产生致命错误

### ISSUE THREAD

**Issue by SHIINASAMA** [XenoAmess/p3c#142]
**Describe the bug**
当我尝试在idea使用通过符号链接打开一个项目时报错，提示致命错误（禁用插件是完全可以正常使用的）

**To Reproduce**
首先有一个符号链接的目录![image](https://user-images.githubusercontent.com/40531369/133885591-600df9da-4a0e-47d4-b1cb-14ef6774d03d.png)

然后打开符号链接目录下的项目
![image](https://user-images.githubusercontent.com/40531369/133885643-85c3f3a3-bcb4-440c-83a1-cbf639504740.png)

打开项目索引完成后随即报错
![image](https://user-images.githubusercontent.com/40531369/133885692-a2089bcf-53e5-4f7c-9f47-9956fbd495d0.png)

**Expected behavior**
按道理应该是能正常识别文件的，估计是没有找到对应文件，使用完整路径打开则可以正常使用

**Screenshots**
![image](https://user-images.githubusercontent.com/40531369/133885692-a2089bcf-53e5-4f7c-9f47-9956fbd495d0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11  21H2 22000.194
 - Software Version: idea ultimate 2021.2.2

**Comment by SHIINASAMA** [comment]
# 补充一下报错信息
```
com.intellij.diagnostic.PluginException: Reported element PsiIdentifier:ImplTaskListener is not from the file 'E:/Documents/Code/RemoteFileSystem/src/main/java/pers/kaoru/rfs/client/transmission/ImplTaskListener.java' the inspection 'AlibabaClassMustHaveAuthor' (class ClassMustHaveAuthorRuleInspection) was invoked for. Message: '【ImplTaskListener】缺少包含@author的注释信息'.
Element containing file: PsiJavaFile:ImplTaskListener.java
Inspection invoked for file: PsiJavaFile:ImplTaskListener.java
 [Plugin: com.alibaba.p3c.xenoamess]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:274)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:91)
	at com.intellij.diagnostic.PluginException.logPluginError(PluginException.java:108)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.createHighlightsForDescriptor(LocalInspectionsPass.java:616)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$addDescriptorIncrementally$13(LocalInspectionsPass.java:481)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by XenoAmess** [comment]
1. 系统是？

2.

你的Code快捷方式不是在E:\Documents下吗

为什么后面打开的是E:\Code\RemoteFileSystem ...

3. 展示下打开的操作过程……我不是太理解`然后打开符号链接目录下的项目`是怎么操作的

**Comment by SHIINASAMA** [comment]
1.系统是Windows 11 21H2 22000.194
2.Code目录不是快捷方式，而是**符号链接**
3.
- 首先有符号链接 "E:\Code" -> "E:\Documents\Code"
- 在Idea欢迎界面选择打开
- 选择目录 "E:\Code" 下的任意一个项目
![image](https://user-images.githubusercontent.com/40531369/135947774-ee5e2b88-63e7-4d63-a967-7570d73defde.png)
个人猜测Idea能够正确识别符号链接，从而使选定的 "E:\Code\RemoteFileSystem" 这个目录转换成 "E:\Documents\Code\RemoteFileSystem"，Idea本身功能使用正常，但是插件不能正确识别

**Comment by XenoAmess** [comment]
> 1.系统是Windows 11 21H2 22000.194 2.Code目录不是快捷方式，而是**符号链接** 3.
> 
> * 首先有符号链接 "E:\Code" -> "E:\Documents\Code"
> * 在Idea欢迎界面选择打开
> * 选择目录 "E:\Code" 下的任意一个项目
>   ![image](https://user-images.githubusercontent.com/40531369/135947774-ee5e2b88-63e7-4d63-a967-7570d73defde.png)
>   个人猜测Idea能够正确识别符号链接，从而使选定的 "E:\Code\RemoteFileSystem" 这个目录转换成 "E:\Documents\Code\RemoteFileSystem"，Idea本身功能使用正常，但是插件不能正确识别

懂了……我抽空看看为什么吧

能修就修
