### ISSUE TITLE
Do not use constructor injection com.alibaba.p3c.idea.component.AliProjectComponent

### ISSUE THREAD

**Issue by jidaojiuyou** [XenoAmess/p3c#380]
**Describe the bug**
java.lang.Throwable: Do not use constructor injection (requestorClass=com.alibaba.p3c.idea.component.AliProjectComponent)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:78)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1041)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:36)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:19)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:181)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:176)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponentsNonBlocking(ComponentManagerImpl.kt:469)
	at com.intellij.openapi.project.impl.ProjectImpl.access$createComponentsNonBlocking(ProjectImpl.kt:57)
	at com.intellij.openapi.project.impl.ProjectImpl$Companion$preloadServicesAndCreateComponents$2.invokeSuspend(ProjectImpl.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

这 ...

**To Reproduce**
一打开idea就报这错误

**Expected behavior**
一打开idea就报这错误

**Screenshots**
![image](https://user-images.githubusercontent.com/24694117/220497997-ce045db6-2093-44d2-b4ff-67468c7feae2.png)

MACOS 13
IDEA 2023.1 EAP

**Comment by XenoAmess** [comment]
我看下

好做就现在 不好做就周末。

主要是EAP 唉 jb家的EAP的质量真的这两年 不能说惨不忍睹吧至少也是没法正常使用

**Comment by XenoAmess** [comment]
……啊这 2023改的有点大啊他们
今早估计是做不完了 周末再看吧

**Comment by XenoAmess** [comment]
可能得单独发个2023版本 跟前面的不太能兼容了 他们升到17了还改了一堆口子23333

**Comment by XenoAmess** [comment]
额 比预想的简单点

提交了，等两天吧

https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-/versions/stable/296829

或者不等了直接下载未审核版本

https://plugins.jetbrains.com/files/14109/296829/Alibaba_Java_Coding_Guidelines-2.1.1.6x-SNAPSHOT.zip

或者你自己去develop分支拿自己编译

**Comment by XenoAmess** [comment]
发现新问题随时再开issue来反馈 @jidaojiuyou

虽然我自己不用EAP了但是只要有人用我还是会尽可能修的

**Comment by jidaojiuyou** [comment]
感谢感谢
