### ISSUE TITLE
idea2024.1  不兼容

### ISSUE THREAD

**Issue by Mrzhugq** [XenoAmess/p3c#564]
**Describe the bug**
idea2024.1 不兼容

**Screenshots**
![image](https://github.com/XenoAmess/p3c/assets/84071063/a6da2c0f-174c-4148-9866-d32536043cc1)

**Desktop (please complete the following information):**
 - OS: win10 21H2
 - Version 2.2.2.0x
 - idea 2024.1

**Additional context**
报错信息
```text
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.alibaba.p3c.idea.action.AliInspectionAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.alibaba.p3c.xenoamess]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```

**Comment by yxdroid** [comment]
也是这个问题导致2024.1版本idea经常奔溃

**Comment by zhang-zhonggui** [comment]
同样的问题导致2.1不兼容
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.alibaba.p3c.idea.action.ToggleProjectInspectionAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.alibaba.p3c.xenoamess]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by yxdroid** [comment]
亲,您的邮件已收到!

**Comment by XenoAmess** [comment]
> 也是这个问题导致2024.1版本idea经常奔溃

你确定一个deprecated而不是removed的策略会导致idea经常崩溃吗
我觉得有点..魔幻
我先看下这个现在新策略需要怎么做哦

**Comment by XenoAmess** [comment]
已解

**Comment by yxdroid** [comment]
亲,您的邮件已收到!
